// <auto-generated />
using System;
using CoreLms.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreLms.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181013022644_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("CoreLms.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfJoining");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<bool>("IsSupervisor");

                    b.Property<DateTime?>("LastDay");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("MidName");

                    b.Property<int?>("SupervisorId");

                    b.HasKey("Id");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("CoreLms.Models.Leave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Balance");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("LeaveTypeId");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("Leave");
                });

            modelBuilder.Entity("CoreLms.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ApprRejDate");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired();

                    b.Property<int>("LeaveTypeId");

                    b.Property<int>("NoOfDays");

                    b.Property<string>("Reason")
                        .IsRequired();

                    b.Property<DateTime>("RequestDate");

                    b.Property<string>("RequestStatus");

                    b.Property<int>("RequestorId");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("RequestorId");

                    b.ToTable("LeaveRequest");
                });

            modelBuilder.Entity("CoreLms.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LeaveType");
                });

            modelBuilder.Entity("CoreLms.Models.Employee", b =>
                {
                    b.HasOne("CoreLms.Models.Employee", "Supervisor")
                        .WithMany("Supervisees")
                        .HasForeignKey("SupervisorId");
                });

            modelBuilder.Entity("CoreLms.Models.Leave", b =>
                {
                    b.HasOne("CoreLms.Models.Employee", "Employee")
                        .WithMany("Leaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreLms.Models.LeaveType", "LeaveTypes")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreLms.Models.LeaveRequest", b =>
                {
                    b.HasOne("CoreLms.Models.LeaveType", "LeaveTypes")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CoreLms.Models.Employee", "Requestor")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("RequestorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
